# Generated by Django 5.1.4 on 2024-12-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_githubstats_collobrators_githubstats_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedart',
            name='quotation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
